// Code generated by hive. DO NOT EDIT.

package rpc

import (
	"fmt"
	"github.com/benka-me/laruche/go-pkg/discover"
	users "github.com/benka-me/users/go-pkg/users"
	"google.golang.org/grpc"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Sprintf("")
var _ = strconv.FormatInt(int64(0), 10)

type Clients struct {
	Users        users.UsersClient
	UsersGateway users.UsersClient
}

func InitClients(engine discover.Engine, options ...grpc.DialOption) Clients {

	connUsers, err := engine.GrpcConn("benka-me/users", false, options...)
	if err != nil {
		panic("Cannot dial")
	}

	connUsersGateway, err := engine.GrpcConn("benka-me/users", true, options...)
	if err != nil {
		panic("Cannot dial")
	}

	return Clients{
		Users:        users.NewUsersClient(connUsers),
		UsersGateway: users.NewUsersClient(connUsersGateway),
	}
}
