version: '3.1'
#graphql bee

services:
  app:
    network_mode: host
    image: golang
    volumes:
      - ${GOPATH}/src:/go/src
      - ${GOPATH}/pkg/mod:/go/pkg/mod
      - ${HOME}/laruche:/root/laruche
    command: go run ${APP_REPO} ${HIVE}
