// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Token string `json:"Token"`
}

type Bee struct {
	Author      string     `json:"Author"`
	Name        string     `json:"Name"`
	PkgName     string     `json:"PkgName"`
	Description string     `json:"Description"`
	Repo        string     `json:"Repo"`
	Port        int        `json:"Port"`
	License     string     `json:"License"`
	Keywords    []string   `json:"Keywords"`
	DevLang     int        `json:"DevLang"`
	Framework   *Framework `json:"Framework"`
	Rpcs        []*RPC     `json:"Rpcs"`
}

type BeeDetails struct {
	Readme string `json:"Readme"`
}

type BeeReq struct {
	Author string `json:"Author"`
	Name   string `json:"Name"`
	Auth   *Auth  `json:"Auth"`
}

type Framework struct {
	Author string `json:"Author"`
	Name   string `json:"Name"`
}

type FullBee struct {
	Bee     *Bee        `json:"Bee"`
	Details *BeeDetails `json:"Details"`
}

type Hive struct {
	Author string `json:"Author"`
	Name   string `json:"Name"`
	Repo   string `json:"Repo"`
}

type Home struct {
	Bees  []*Bee  `json:"Bees"`
	Hives []*Hive `json:"Hives"`
}

type HomeReq struct {
	Token string `json:"Token"`
}

type LoginRes struct {
	Status   bool   `json:"Status"`
	TokenErr string `json:"TokenErr"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterRes struct {
	Status        bool   `json:"Status"`
	StatusMessage string `json:"StatusMessage"`
}

type RPC struct {
	Name   string `json:"Name"`
	Input  string `json:"Input"`
	Output string `json:"Output"`
	Line   string `json:"Line"`
}
